---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-nfs-pvc
  namespace: database-common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nas-nfs
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: database-common
  name: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-root-password
                  key: password
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command:
              - pg_isready
              - -U
              - postgres
          volumeMounts:
            - name: pgsql-pvc
              mountPath: /var/lib/postgresql/data
            - name: pgsql-conf
              mountPath: /usr/share/postgresql/postgresql.conf
              subPath: postgresql.conf
      # securityContext:
      #   runAsUser: 1000
      #   fsGroup: 1000
      volumes:
        - name: pgsql-pvc
          persistentVolumeClaim:
            claimName: pgsql-nfs-pvc
        - name: pgsql-conf
          configMap:
            name: pgsql-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: database-common
  labels:
    app: pgsql
spec:
  type: NodePort
  ports:
    - nodePort: 30002
      port: 5432
      name: mysql
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresql