apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-cache-deployment
  namespace: container-basis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-cache
  template:
    metadata:
      labels:
        app: image-cache
    spec:
      containers:
      - name: reg-gcr
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        image: yangchuansheng/registry-proxy:latest
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: PROXY_REMOTE_URL
          value: https://gcr.io
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: image-cache-pvc
          mountPath: /var/lib/registry
          # subPath: gcr
      - name: reg-hub
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        image: yangchuansheng/registry-proxy:latest
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5001
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: PROXY_REMOTE_URL
          value: https://registry-1.docker.io
        - name: PROXY_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhub-account
              key: uername
        - name: PROXY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhub-account
              key: password
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: image-cache-pvc
          mountPath: /var/lib/registry
          # subPath: hub
      - name: reg-k8s-gcr
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        image: yangchuansheng/registry-proxy:latest
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5002
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: PROXY_REMOTE_URL
          value: https://k8s.gcr.io
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: image-cache-pvc
          mountPath: /var/lib/registry
          # subPath: k8s-gcr
      - name: reg-quay
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        image: yangchuansheng/registry-proxy:latest
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5003
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: PROXY_REMOTE_URL
          value: https://quay.io
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: image-cache-pvc
          mountPath: /var/lib/registry
          # subPath: hub      
      volumes:
      - name: image-cache-pvc
        persistentVolumeClaim:
          claimName: shared-image-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-cache-service
  namespace: container-basis
spec:
  selector:
    app: image-cache
  ports:
    - protocol: TCP
      port: 5000
      name: gcr
    - protocol: TCP
      port: 5001
      name: hub
    - protocol: TCP
      port: 5002
      name: k8s-gcr
    - protocol: TCP
      port: 5003
      name: quay

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress-aio
  namespace: container-basis
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: gcr-k3s.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: image-cache-service
            port:
              number: 5000
  - host: hub-k3s.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: image-cache-service
            port:
              number: 5001
  - host: k8s-gcr-k3s.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: image-cache-service
            port:
              number: 5002
  - host: quay-k3s.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: image-cache-service
            port:
              number: 5003

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-image-cache-pvc
  namespace: container-basis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nas-nfs
  volumeMode: Filesystem