apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress
  namespace: logging
spec:
  rules:
  - host: logging.k3.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: loki-headless
            port: 
              number: 3100
