---
apiVersion: v1
kind: Service
metadata:
  name: k8s-quay-registry-svc
  namespace: container-basis
  labels:
    run: k8s-quay-registry
spec:
  selector:
    app: k8s-quay-registry
  ports:
    - protocol: TCP
      port: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress-k8s-quay
  namespace: container-basis
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: quay-k3s.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: k8s-quay-registry-svc
            port:
              number: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-quay-registry
  namespace: container-basis
  labels:
    app: k8s-quay-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-quay-registry
  template:
    metadata:
      labels:
        app: k8s-quay-registry
    spec:
      containers:
      - name: k8s-quay-registry
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: "512Mi"
            cpu: "500m"
        image: yangchuansheng/registry-proxy:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - name: local
          mountPath: /var/lib/registry
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: PROXY_REMOTE_URL
          value: https://quay.io
      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: registry-pvc
