apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-r4y-prod
  namespace: default
spec:
  secretName: local-r4y-prod
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.r4y.site"
  dnsNames:
    - "local.r4y.site"
    - "*.local.r4y.site"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-r4y-admin-prod
  namespace: default
spec:
  secretName: local-r4y-admin-prod
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.admin.r4y.site"
  dnsNames:
    - "admin.r4y.site"
    - "*.admin.r4y.site"