---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-writefreely-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nas-nfs
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writefreely-web
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writefreely-web
  template:
    metadata:
      labels:
        app: writefreely-web
    spec:
      containers:
      - name: writefreely-web
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        image: writeas/writefreely:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-data
          mountPath: /go/keys
          subPath: keys
        - name: web-data
          mountPath: /go/config.ini
          subPath: config.ini
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: pvc-writefreely-data
---
apiVersion: v1
kind: Service
metadata:
  name: writefreely-web
  namespace: homelab
spec:
  selector:
    app: writefreely-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homelab
  annotations:
    spec.ingressClassName: "traefik"
  name: writefreely-web
spec:
  rules:
  - host: writefreely.local.r4y.site
    http:
      paths:
      - backend:
          service:
            name: writefreely-web
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - writefreely.local.r4y.site
    secretName: local-r4y-prod