---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs-pvc
  namespace: database-common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nas-nfs
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: database-common
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: password
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-conf
              mountPath: /etc/mysql/conf.d
      # securityContext:
      #   runAsUser: 1000
      #   fsGroup: 1000
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-nfs-pvc
        - name: mysql-conf
          configMap:
            name: mysql-config

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: database-common
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 3306
      name: mysql
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql